<?php
/**
 * TranslationStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Squidex\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Squidex\Client\Model;
use \Squidex\Client\ObjectSerializer;

/**
 * TranslationStatus Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Squidex\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TranslationStatus
{
    /**
     * Possible values of this enum
     */
    public const TRANSLATED = 'Translated';

    public const LANGUAGE_NOT_SUPPORTED = 'LanguageNotSupported';

    public const NOT_TRANSLATED = 'NotTranslated';

    public const NOT_CONFIGURED = 'NotConfigured';

    public const UNAUTHORIZED = 'Unauthorized';

    public const FAILED = 'Failed';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TRANSLATED,
            self::LANGUAGE_NOT_SUPPORTED,
            self::NOT_TRANSLATED,
            self::NOT_CONFIGURED,
            self::UNAUTHORIZED,
            self::FAILED
        ];
    }
}


