<?php
/**
 * SchemasApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SchemasApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SchemasApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for schemaFieldsDeleteField
     *
     * Delete a schema field..
     *
     */
    public function testSchemaFieldsDeleteField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsDeleteNestedField
     *
     * Delete a nested field..
     *
     */
    public function testSchemaFieldsDeleteNestedField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsDisableField
     *
     * Disable a schema field..
     *
     */
    public function testSchemaFieldsDisableField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsDisableNestedField
     *
     * Disable a nested field..
     *
     */
    public function testSchemaFieldsDisableNestedField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsEnableField
     *
     * Enable a schema field..
     *
     */
    public function testSchemaFieldsEnableField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsEnableNestedField
     *
     * Enable a nested field..
     *
     */
    public function testSchemaFieldsEnableNestedField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsHideField
     *
     * Hide a schema field..
     *
     */
    public function testSchemaFieldsHideField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsHideNestedField
     *
     * Hide a nested field..
     *
     */
    public function testSchemaFieldsHideNestedField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsLockField
     *
     * Lock a schema field..
     *
     */
    public function testSchemaFieldsLockField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsLockNestedField
     *
     * Lock a nested field..
     *
     */
    public function testSchemaFieldsLockNestedField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsPostField
     *
     * Add a schema field..
     *
     */
    public function testSchemaFieldsPostField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsPostNestedField
     *
     * Add a nested field..
     *
     */
    public function testSchemaFieldsPostNestedField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsPutField
     *
     * Update a schema field..
     *
     */
    public function testSchemaFieldsPutField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsPutNestedField
     *
     * Update a nested field..
     *
     */
    public function testSchemaFieldsPutNestedField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsPutNestedFieldOrdering
     *
     * Reorder all nested fields..
     *
     */
    public function testSchemaFieldsPutNestedFieldOrdering()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsPutSchemaFieldOrdering
     *
     * Reorder all fields..
     *
     */
    public function testSchemaFieldsPutSchemaFieldOrdering()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsPutSchemaUIFields
     *
     * Configure UI fields..
     *
     */
    public function testSchemaFieldsPutSchemaUIFields()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsShowField
     *
     * Show a schema field..
     *
     */
    public function testSchemaFieldsShowField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemaFieldsShowNestedField
     *
     * Show a nested field..
     *
     */
    public function testSchemaFieldsShowNestedField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemasDeleteSchema
     *
     * Delete a schema..
     *
     */
    public function testSchemasDeleteSchema()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemasGetSchema
     *
     * Get a schema by name..
     *
     */
    public function testSchemasGetSchema()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemasGetSchemas
     *
     * Get schemas..
     *
     */
    public function testSchemasGetSchemas()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemasPostSchema
     *
     * Create a new schema..
     *
     */
    public function testSchemasPostSchema()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemasPublishSchema
     *
     * Publish a schema..
     *
     */
    public function testSchemasPublishSchema()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemasPutCategory
     *
     * Update a schema category..
     *
     */
    public function testSchemasPutCategory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemasPutPreviewUrls
     *
     * Update the preview urls..
     *
     */
    public function testSchemasPutPreviewUrls()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemasPutRules
     *
     * Update the rules..
     *
     */
    public function testSchemasPutRules()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemasPutSchema
     *
     * Update a schema..
     *
     */
    public function testSchemasPutSchema()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemasPutSchemaSync
     *
     * Synchronize a schema..
     *
     */
    public function testSchemasPutSchemaSync()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemasPutScripts
     *
     * Update the scripts..
     *
     */
    public function testSchemasPutScripts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for schemasUnpublishSchema
     *
     * Unpublish a schema..
     *
     */
    public function testSchemasUnpublishSchema()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
